### ISSUE TITLE
无法获取SHA1链接

### ISSUE THREAD

**Issue by csc-x** [Nerver4Ever/SevenSha1UIAdvancedHelper#10]
点击获取SHA1按钮时无任何反应

![image](https://user-images.githubusercontent.com/56724863/170259027-32085d7a-9c43-4878-be0d-086d05875ddc.png)
![image](https://user-images.githubusercontent.com/56724863/170259228-025e0f5c-5a14-46a9-afef-2dc1b2f0fff6.png)

**Comment by csc-x** [comment]
解决了， 原来是unpkg.com 的国内镜像地址无法访问。
将以下四个依赖库中unpkg.zhimg.com改为unpkg.com即可
https://unpkg.zhimg.com/underscore@1.12.0/underscore-min.js
https://unpkg.zhimg.com/sweetalert2@11.3.0
https://unpkg.zhimg.com/node-forge@0.10.0/dist/forge.min.js
https://unpkg.zhimg.com/emoutils@2.0.0/dist/umd/emoutils.min.js

**Comment by lonlycar** [comment]
> 解决了， 原来是unpkg.com 的国内镜像地址无法访问。 将以下四个依赖库中unpkg.zhimg.com改为unpkg.com即可 https://unpkg.zhimg.com/underscore@1.12.0/underscore-min.js https://unpkg.zhimg.com/sweetalert2@11.3.0 https://unpkg.zhimg.com/node-forge@0.10.0/dist/forge.min.js https://unpkg.zhimg.com/emoutils@2.0.0/dist/umd/emoutils.min.js

兄弟怎么解决的？我这换成unpkg.com也没有获取sha1连接按钮呀
