### ISSUE TITLE
大小为0的文件提示“格式生成失败”

### ISSUE THREAD

**Issue by microka** [Nerver4Ever/SevenSha1UIAdvancedHelper#12]
115网盘中存在一些大小为0的空文件 `115://sample.txt|0|DA39A3EE5E6B4B0D3255BFEF95601890AFD80709|DA39A3EE5E6B4B0D3255BFEF95601890AFD80709`
如果文件夹中存在此类空文件，对该文件夹生成sha1链接文件时，虽然提示所有文件都生成成功，但打开生成的sha1文本，空文件是显示为“格式生成失败!”。

有两个想法，不知能否实现？
1、当导出的文件中存在这类空文件时，在最后输出的结果统计中进行提醒（如空文件X个）
2、生成的sha1文本中，将“格式生成失败!”替换为空文件的实际sha1链接“`115://实际文件名|0|DA39A3EE5E6B4B0D3255BFEF95601890AFD80709|DA39A3EE5E6B4B0D3255BFEF95601890AFD80709`”

脚本与环境信息：（如果报bug，请附带上如下信息） [gm]:Tampermonkey [gmVersion]:4.16.1 [ua]:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 [version]:143.2022.0402.1

**Comment by Nerver4Ever** [comment]
有时间会增加这样的功能，直接将大小为0的剔除
