### ISSUE TITLE
今天0606开始115可能调整了策略。遇到了block提示

### ISSUE THREAD

**Issue by wildwolfzj** [Nerver4Ever/SevenSha1UIAdvancedHelper#14]
115mac 25.009
TamperMonkey v4.16.1
本脚本 v3.5
自己拆分了大包txt
每个约5k行
期间没用其他上传下载操作。（容易提示block半小时）

昨晚还好的。一般连续导入3个才会提示，而且退出登陆重新登陆就好

今天继续操作，但是连续到2k多的时候就block了，重新登陆，还是2k多。

不知道是触发了我个人的block，还是115修改了block规则

是否能提前判断转存条数，增加sleep间隔和频次。
或者设置几个开关，方便手动调控。

**Comment by lyhfree** [comment]
我这也碰到了，拆分成六千多条才行，而且还是弹出了两个文件可能上传失败提示，但是最终结束时还是全部上传成功了
