### ISSUE TITLE
[建议]遇到115限时上传，直接停止

### ISSUE THREAD

**Issue by wildwolfzj** [Nerver4Ever/SevenSha1UIAdvancedHelper#15]
我看提示115限制，请立刻停止的提示。
不知道脚本能不能抓到这个错误。否则不注意，还在一直上传，很容易被官方抓包
如果能识别115限制上传。能否立刻停止脚本，或者直接跳过后续所有的操作。
打印第一次错误的位置即可。
望采纳。

**Comment by WertherHu** [comment]
代码重构后会加入此功能
