### ISSUE TITLE
115新建磁力链接的界面选框过小

### ISSUE THREAD

**Issue by kkz12156** [Nerver4Ever/SevenSha1UIAdvancedHelper#17]
大佬可以调整下添加链接任务那个选框的大小和填写磁力链那个界面的大小吗 感觉使用起来不太方便 磁力多了假如说想修改的话半天都找不到 。。。。或者能否告知下修改代码哪一段自行修改也行  感谢大佬

**Comment by Nerver4Ever** [comment]
建议磁力自己放记事本修改
再调整大小，保存位置下拉框中的选择其他位置，有些分辨率下可能无法点击
