### ISSUE TITLE
出现：可能参数不正确(?)：文件大小超出单文件上传最大限制，无法上传本文件。

### ISSUE THREAD

**Issue by rachelosy** [Nerver4Ever/SevenSha1UIAdvancedHelper#18]
**描述一下遇到的问题**
出现：可能参数不正确(?)：文件大小超出单文件上传最大限制，无法上传本文件。

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

115://刺猬索尼克2 [4K HDR+国配+繁英韩字幕].Sonic.the.Hedgehog.2.2022.2160p.WEB-DL.DDP5.1.HDR.H265-HAMR[13.01G].mkv|13970574120|F7E42F4848CB39A8C28813A229B45EEE9A234565|D2E7675F053DC1DACA536E3EA021391553010E1F

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的
![image](https://user-images.githubusercontent.com/55753935/174220752-b23a0094-007d-4cdb-9462-0383c890a814.png)

**Comment by Nerver4Ever** [comment]
遇到问题，先搜索一下是个好习惯。 #1

**Comment by aucifer112** [comment]
这个问题有人解答吗
