### ISSUE TITLE
重命名过程中卡住，请求报错

### ISSUE THREAD

**Issue by yuzunyue** [Nerver4Ever/SevenSha1UIAdvancedHelper#2]
// 页面
![image](https://user-images.githubusercontent.com/32872977/165726000-45a9e5ca-8d73-4399-b950-d873a1cc41f5.png)
// 报错接口
![image](https://user-images.githubusercontent.com/32872977/165726106-170a9eaa-35b2-4946-9bf7-9c25746290b5.png)
// 报错内容
![image](https://user-images.githubusercontent.com/32872977/165726157-bd4324f1-a8ea-47c1-a127-f85c38ff8fc4.png)
偶发出现，不是必现BUG，希望可以加一下判断，出现的时候再重新请求

**Comment by Nerver4Ever** [comment]
out of free disk space 应该不是这个重命名出来的报错。

现在重命名遇到问题，可以打开“去除分隔符”（设置中），进行手动执行去除。
