### ISSUE TITLE
点击“链接与sha1转存任务”按钮后，弹出框内没有“转存按钮”

### ISSUE THREAD

**Issue by TangXiangLong** [Nerver4Ever/SevenSha1UIAdvancedHelper#20]
1、版本
脚本版本： 2022.06.16 更新，115转存助手ui优化版 v3.6 (143.2022.0616.1)
chrome版本： 102.0.5005.115（正式版本） （64 位）
115版本：chrome浏览器登录
2、问题描述
点击“链接与sha1转存任务”按钮后，右下角只出现“开始下载”按钮，并没有转存按钮

**Comment by tongtian-jiaozhu** [comment]
我的也是出现这种状况，但是换一台电脑就没有问题了。目前不知道需要提交什么数据能帮到大神

**Comment by tongtian-jiaozhu** [comment]
> 1、版本 脚本版本： 2022.06.16 更新，115转存助手ui优化版 v3.6 (143.2022.0616.1) chrome版本： 102.0.5005.115（正式版本） （64 位） 115版本：chrome浏览器登录 2、问题描述 点击“链接与sha1转存任务”按钮后，右下角只出现“开始下载”按钮，并没有转存按钮

我解决了，需要改脚本里前面的几个网址：
代码中开头几个改为如下

https://unpkg.com/underscore@1.12.0/underscore-min.js
https://unpkg.com/sweetalert2@11.3.0
https://unpkg.com/node-forge@0.10.0/dist/forge.min.js
https://unpkg.com/emoutils@2.0.0/dist/umd/emoutils.min.js


可以参考之前的问题
[https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/issues/5](url)

**Comment by TangXiangLong** [comment]
非常感谢！问题解决了

**Comment by pnixnoyo** [comment]
> 

改了网址还是不行。。

**Comment by 7peanuts** [comment]
v3.8.1 修改 require 后，还是不能显示提取按钮
```js
// @require      https://unpkg.com/underscore@1.12.0/underscore-min.js
// @require      https://unpkg.com/sweetalert2@11.3.0
// @require      https://unpkg.com/node-forge@0.10.0/dist/forge.min.js
// @require      https://unpkg.com/emoutils@2.0.0/dist/umd/emoutils.min.js
```
