### ISSUE TITLE
开启分隔符和还原文件名后，脚本一直转圈

### ISSUE THREAD

**Issue by yuesfds** [Nerver4Ever/SevenSha1UIAdvancedHelper#21]
脚本与环境信息：（如果报bug，请附带上如下信息） [gm]:Tampermonkey [gmVersion]:4.16.1 [ua]:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 [version]:143.2022.0402.1

勾选开启分隔符和去除分隔符后，脚本就一直转圈没动静，一旦取消这俩选项后，脚本就能正常运作了

**Comment by Nerver4Ever** [comment]
检查 https://unpkg.com/emoutils@2.0.0/dist/umd/emoutils.min.js 能不能访问
参看 #20 中的解决方案

**Comment by yuesfds** [comment]
问题解决了，感谢大佬。另外问一下转存的速度是取决于什么
