### ISSUE TITLE
能否加个自动添加后缀的“.”功能

### ISSUE THREAD

**Issue by ppllpig** [Nerver4Ever/SevenSha1UIAdvancedHelper#23]
115已无法离线和上传很多资源，本地上传也只能通过删除后缀的点（.）再上传，能否去除分隔符功能的基础上加个添加后缀的点功能。

**Comment by Nerver4Ever** [comment]
本地文件，扩展名加个分隔符就行了。。。。

**Comment by jl0476** [comment]
> 本地文件，扩展名加个分隔符就行了。。。。

传到115之后，扩展名修改不了了？
请问有什么解决方案吗

**Comment by Nerver4Ever** [comment]
本地文件，建议用分隔符添加到后缀，那样就可以用助手“去除分隔符”了

**Comment by 78776** [comment]
现在还能通过改后缀名的方式直接绕过和谐上传吗
