### ISSUE TITLE
含违规内容上传失败是文件的原因吗

### ISSUE THREAD

**Issue by lhs55502002a** [Nerver4Ever/SevenSha1UIAdvancedHelper#25]
**描述一下遇到的问题**
 可能参数不正确(?)：上传失败，含违规内容
这是转存的文件的问题还是插件的问题？是现在不能转存违规内容了吗

**复现问题**
[1.[ [如[有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1]
115://@@Angel Dreamgirl_sha1.txt|19093|8545ED006C495F349DAD66C751A7BC0C896CDCB4|8545ED006C495F349DAD66C751A7BC0C896CDCB4
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”
油猴版本：V4.16.1
浏览器版本:Chrome 版本 103.0.5060.53（正式版本） （64 位）(到2022.6.26为止最新版）
运行环境：WIN11

**截图**
1.如有可能附上提示出错截图
<img width="515" alt="image" src="https://user-images.githubusercontent.com/108201940/175795189-9d7ce641-a94d-466b-a99b-4f7575c27fee.png">

2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795615-9175ac2f-41db-4e99-b3e9-1106c7ae2857.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795634-009d4302-f3ef-4251-8907-167ecc032f2f.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795637-47ac4e93-00ad-4837-84a4-bc31348c4023.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795643-f9569f7f-01c2-4447-aa94-5822d8cb2224.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795645-321dfebf-eadd-488a-9859-1560c431909e.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795649-820f0772-6637-4cb9-a1b4-3213efb2405b.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795710-a39f8549-cb51-4dd9-a19b-42716a671017.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795722-cbbd6419-826d-495d-892d-453f556b9e07.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795726-33e4bf6c-dd59-45d8-8d36-52e7bd1c34dc.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795727-47a46e9e-7ffa-44e9-a9d1-5f9a73b0ba33.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795729-a8dccc61-49df-4207-8a45-ee4d0a292a0a.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795741-56aa840a-4769-47e5-ae34-03e235b012cc.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795745-a226659c-075b-44af-9c3c-b525743672f9.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795750-4a925b56-c3f9-4e03-a785-9c6f21b393dc.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795756-561c9ecb-420b-49f8-8789-41b6d4c53491.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795765-181c4368-9a23-4497-8795-b0c31a597395.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795777-3cd5f89d-4ebf-4326-a886-c9511bc1e28d.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795781-071edf6c-bd46-462a-8930-1b1128320c84.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795789-1a03e4f6-2635-4bcf-afdb-1a017260670a.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795792-a19a373e-80ba-451b-b373-9944ba66b360.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795793-f95d2062-5319-4eb9-b31e-3c7bf01a6f90.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/108201940/175795798-addb6c2b-e295-427f-b0ea-67d0a3053bb2.png">

**Comment by Nerver4Ever** [comment]
升级3.6

建议下次遇到问题,先看看版本.以及新版本是否涉及到你的问题.
