### ISSUE TITLE
文件上传一直卡在创建文件夹这一步 

### ISSUE THREAD

**Issue by Ahaolin** [Nerver4Ever/SevenSha1UIAdvancedHelper#26]
**描述一下遇到的问题**
文件上传一直卡在创建文件夹这一步 ,执行uploadinfo接口失败，不动了
在此输入问题
![image](https://user-images.githubusercontent.com/37574890/176929726-be13216b-5a2b-4305-9914-bf38f225b637.png)

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
115://HARU-002 わたしのパンストつま先を舐めて下さい。.jpg|162861|0D676BE9CB8A0751C426D360A3530F827BBC7992|EE5DC5981500B8DCC318E6A2F297281823F9316D
3. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”
油猴 v4.16.1  浏览器 115浏览器(v25.0.2.1) 脚本(v3.6)

**截图**
1.如有可能附上提示出错截图
![image](https://user-images.githubusercontent.com/37574890/176930051-ecaf4874-ff5a-4764-80bc-10a391e18f2f.png)
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的
![image](https://user-images.githubusercontent.com/37574890/176930135-f3a3a76b-d87b-412b-a80d-a3c53ee794e3.png)

**Comment by Nerver4Ever** [comment]
应该是网络问题导致依赖库有问题。尝试参考一下：
#20 
#5 
等，检查依赖库能否正常访问。

**Comment by Ahaolin** [comment]
![image](https://user-images.githubusercontent.com/37574890/177005708-5137e10b-6dca-401d-8e96-a60daed75b4e.png)
昨天已经改过了 ，还是不行，不知道为啥
