### ISSUE TITLE
提取115文件undefined 

### ISSUE THREAD

**Issue by captain101213** [Nerver4Ever/SevenSha1UIAdvancedHelper#28]
**描述一下遇到的问题**
在此输入问题提取115文件失败显示原因undefined  个别文件提取成功
![36D31379-53DA-45DE-BF45-40E6686211F5](https://user-images.githubusercontent.com/108579170/177002593-f3458d86-40fc-4165-918d-905d286b30ac.jpeg)
![486E5479-BDE0-4837-A0CE-2C1CA4884E2B](https://user-images.githubusercontent.com/108579170/177002598-b6de7d5f-5142-451b-8395-3f1d1b10ee52.jpeg)
![4AF868D0-FC2F-4ABA-8E0E-4DFCB4026676](https://user-images.githubusercontent.com/108579170/177002600-4443ef50-4446-4ba8-ac60-21b662e3c66f.jpeg)
![1254FE28-FD6B-4E1C-9704-37288B84E200](https://user-images.githubusercontent.com/108579170/177002606-14ae130d-9673-49a2-8b5f-af642ece36c6.jpeg)
![0BBA8F24-E824-40BA-869A-2051D585165A](https://user-images.githubusercontent.com/108579170/177002628-fb5b1ce7-bf59-4887-875e-92256a42327d.jpeg)
![Uploading AFE22AF8-33FD-4331-9EAD-16E0F4268813.jpeg…]()
成功

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的

**Comment by captain101213** [comment]
大部分文件都不能提取提示undefined  部分广告图片和txt能提取

**Comment by Nerver4Ever** [comment]
未对foxok进行兼容性检测。
ios上可尝试使用拦截100或者gear进行使用。
