### ISSUE TITLE
转存文件不显示转存界面

### ISSUE THREAD

**Issue by GC-white** [Nerver4Ever/SevenSha1UIAdvancedHelper#29]
**更新到3.6之后，转存任何文件都不显示之前的转存界面，点了之后一点反应没有，能正常转存，但是没法判断资源有没有转存完成**

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”
油猴 v4.16.1 浏览器 115浏览器(v25.0.2.1) 脚本(v3.6)

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的
![115截图20220707103741](https://user-images.githubusercontent.com/108848249/177678999-9e8c4735-5112-407d-bcd2-c304edfafb6e.png)

**Comment by WertherHu** [comment]
先搜索或者浏览下已有的问题。看看是不是跟你一样。
类似参看 #20

**Comment by mafia233** [comment]
我也遇到这种情况了
https://wwt.lanzoul.com/iJuKZ07n27sd
这个是录频文件，结尾有相关版本号内容

**Comment by Nerver4Ever** [comment]
网络问题，查看一下依赖库能否访问，#20
