### ISSUE TITLE
转存出现    频繁请求，被115限制 （立即停止，尝试停止操作半小时或者重新登录）：Not Allowed

### ISSUE THREAD

**Issue by Nerver4Ever** [Nerver4Ever/SevenSha1UIAdvancedHelper#3]
*描述一下遇到的问题
转存出现    频繁请求，被115限制 （立即停止，尝试停止操作半小时或者重新登录）：Not Allowed

**Comment by Nerver4Ever** [comment]
频繁请求（短时间过快上传，或者遇到115服务器高峰期）出现

[解决方案]
立即停止上传！！尝试停止操作半小时或者重新登录。或者有需求联系115客服！

后续会更新放慢上传（转存）频率

**Comment by ysy5779** [comment]
感谢大佬，希望能尽快更新，最近好多资源都转存不了了一直提示

**Comment by lyhfree** [comment]
能否加个调节上传速度设置，可以让用户自己设置上传，出现115限制后可以让用户自己先更改上传速度
