### ISSUE TITLE
安装最新版的转存助手 在115浏览器内不展示助手的相关操作按钮

### ISSUE THREAD

**Issue by xiaoadong521** [Nerver4Ever/SevenSha1UIAdvancedHelper#30]
**描述一下遇到的问题**
在此输入问题
安装最新版的转存助手 在115浏览器内不展示助手的相关操作按钮
**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
![屏幕截图 2022-07-11 221413](https://user-images.githubusercontent.com/39687724/178284874-625bcaf5-b3c4-4eb3-bfb3-3784e2b2b4db.png)

**Comment by Nerver4Ever** [comment]
网络问题，参考 #20 

下次遇到问题，现在issue里搜索或者查看一下，有没有类似的。
