### ISSUE TITLE
3.6版本已失效

### ISSUE THREAD

**Issue by xzbill** [Nerver4Ever/SevenSha1UIAdvancedHelper#31]
Chrome 102.0.5005.61(MacOS & Windows)
115网页版3.6版本

选择链接与sha1转存任务按钮，弹出原始界面，没有原先的界面。此外，用3.5版本是可以sha1转存，但容易出错。我记得上周3.6版本仍然是可以正常使用的。

**Comment by xzbill** [comment]
![2](https://user-images.githubusercontent.com/42631669/179809844-23dd764d-2bad-4db2-aa5b-79b79a7b6d5a.png)
![1](https://user-images.githubusercontent.com/42631669/179809863-51893d51-9315-4d5c-9d6f-b9c74e3a6523.png)

**Comment by Nerver4Ever** [comment]
参考 #20 

下次有问题，先搜索一下。
