### ISSUE TITLE
磁链转换不了

### ISSUE THREAD

**Issue by mice4869** [Nerver4Ever/SevenSha1UIAdvancedHelper#34]
**描述一下遇到的问题**
在此输入问题

**复现问题**
1. 想把磁链转换过去 无法成功
2.
![image](https://user-images.githubusercontent.com/31395433/182009162-93c6f295-c5cb-448f-a690-580a6646e53a.png)

**截图**
![image](https://user-images.githubusercontent.com/31395433/182009142-85a0460b-93d6-4061-bbea-ad6cdb967052.png)

**Comment by Nerver4Ever** [comment]
啊这。。。从来没有过这个功能啊= =！
