### ISSUE TITLE
拓展名部分分隔符无法去除

### ISSUE THREAD

**Issue by muguou** [Nerver4Ever/SevenSha1UIAdvancedHelper#37]
上传后的自动去除分隔符
和手动去除分隔符。
或者手动通过115重命名都无法更改扩展名。

可能是115改版，禁止更改扩展名，可能需要改程序了

**Comment by lydygg** [comment]
附议，我刚试了半天都不行，上午好像还可以的，纳闷

**Comment by Nerver4Ever** [comment]
后缀名不能去除，新bug。已经能复现。正想新方案解决。

**Comment by lydygg** [comment]
> 后缀名不能去除，新bug。已经能复现。正想新方案解决。

辛苦

**Comment by muguou** [comment]
> 后缀名不能去除，新bug。已经能复现。正想新方案解决。

辛苦，提供思路，添加分隔符时，在拓展名部分不添加分隔符。毕竟拓展名不可能违规。

**Comment by muguou** [comment]
> 后缀名不能去除，新bug。已经能复现。正想新方案解决。

// 辛苦，提供思路，添加分隔符时，在拓展名部分不添加分隔符。毕竟拓展名不可能违规。

刚尝试完。这个方案失败，不改扩展名，只改名字会上传失败，提示违规。

在尝试，去掉扩展名，上传完毕后再添加拓展名

**Comment by muguou** [comment]
> 

这个方案成功，可以实现

**Comment by muguou** [comment]
> > 后缀名不能去除，新bug。已经能复现。正想新方案解决。
> 
> // 辛苦，提供思路，添加分隔符时，在拓展名部分不添加分隔符。毕竟拓展名不可能违规。
> 
> 刚尝试完。这个方案失败，不改扩展名，只改名字会上传失败，提示违规。
> 
> 在尝试，去掉扩展名，上传完毕后再添加拓展名

先上传无扩展名文件，后添加扩展名，已尝试，这个方案可以实现。

**Comment by muguou** [comment]
不太懂js，借着搜索引擎改了两个函数，可以用


    async function processRename(targetFolderCid, separator, sleepTime, resultCallback) {
        let onlineFiles = new Array();
        await getAllFiles(targetFolderCid, onlineFiles, targetFolderCid, (fname, pIndex) => {
            if (pIndex > 1) {
                resultCallback && resultCallback({
                    state: true,
                    msg: `正在获取 【${fname}】 下第 ${pIndex} 页的内容...`
                });
            } else {
                resultCallback && resultCallback({
                    state: true,
                    msg: `正在获取 【${fname}】 下的内容...`
                });
            }
        });


        let selectedFiles = onlineFiles.filter(f => f.name.search(separator) != -1).map(f => {
            //let lastIndex=f.name.lastIndexOf(".");
            //let name=f.name.substring(0,lastIndex);
            //let ext=f.name.substring(lastIndex+1);

            let fo = {
                id: f.id,
                //name: name.split(separator).join("")+"."+reverseString(ext)
                name:f.name.split(separator).join("")
            };
            return fo;
        });


        selectedFiles = selectedFiles.map(f => {
            //let lastIndex=f.name.lastIndexOf(".");
            //let name=f.name.substring(0,lastIndex);
            //let ext=f.name.substring(lastIndex+1);

            let fo = {
                id: f.id,
                //name: name.split(separator).join("")+"."+reverseString(ext)
                name:f.name.replace("迡" , ".")
            };
            return fo;
        });



        let i, j, temporary, chunk = 115;
        for (i = 0, j = selectedFiles.length; i < j; i += chunk) {
            temporary = selectedFiles.slice(i, i + chunk);
            resultCallback && resultCallback({
                state: true,
                msg: `正在重命名第${i + 1}到${i + temporary.length}个文件...`
            });
            let renameResult = await renameFiles(temporary);
            if (renameResult.state === true) {
                resultCallback && resultCallback({
                    state: true,
                    msg: `重命名第${i + 1}到${i + temporary.length}个文件成功!`
                });
            } else {
                resultCallback && resultCallback({
                    state: false,
                    msg: renameResult.error
                });
                resultCallback && resultCallback({
                    state: true,
                    msg: `重命名第${i + 1}到${i + 1 + temporary.length}个文件中有失败！！!`
                });
            }
            await delay(sleepTime);
        }

    }

    function parseSha1LinksToFileArray(text, nameSeparator, errorCallback) {
        let textLines = text.split(/\r?\n/);

        let files = new Array();
        for (let line of textLines) {
            let fLine = line.trim();
            if (!fLine) continue;
            let r = convertFromSha1Link(fLine);
            if (r.state) {
                //let nameStrings = r.fileItem.name.split(".");
                //let extension = nameStrings.pop();
                //r.fileItem.extension = extension;
                //let formatedExtension=reverseString(extension);
                //根据配置重新设置文件名
                if (nameSeparator) {
                    //使用emoutils.js库来分割，带有emoji的文件名
                    //let fileName = emojiUtils.toArray(nameStrings.join('.')).map(c => c + nameSeparator).join("").slice(0, -1);
                    //r.fileItem.formatedName = fileName + "." + formatedExtension;
                    let newName = r.fileItem.name.split(".");
                    let newName2 =emojiUtils.toArray(newName[0]).map(c => c + nameSeparator).join("").slice(0, -1);
                    let newName3 = newName2 + "迡" + newName.pop();


                    //r.fileItem.formatedName=emojiUtils.toArray(r.fileItem.name).map(c => c + nameSeparator).join("").slice(0, -1);
                    r.fileItem.formatedName = newName3;

                } else {
                    r.fileItem.formatedName = r.fileItem.name;
                }
                files.push(r.fileItem);
            } else {
                errorCallback && errorCallback(`${fLine} 格式错误?`);
            }

        }

        return files;
    }

**Comment by logxing** [comment]
有一个方案可行，本地先删除文件名中所有的点字符.       这就去除了扩展名，传完后把点插入到倒数第四位。只不过其他位置的点就丢失了，除非你预先保存了所有的原始文件名。

**Comment by logxing** [comment]
不过115既然把改扩展名的功能废了，说明目的就是加强视频（以及其他可在线看的）文件审核力度，即使绕过，没多久它又会加强了

**Comment by PhoenixZhong** [comment]
> 有一个方案可行，本地先删除文件名中所有的点字符. 这就去除了扩展名，传完后把点插入到倒数第四位。只不过其他位置的点就丢失了，除非你预先保存了所有的原始文件名。

有些文件扩展名不止3位，比如分卷压缩文件，RMVB文件等。

**Comment by ForeverXXL** [comment]
大佬更新的版本是去除了后缀吗?要自己手动添加?

**Comment by PhoenixZhong** [comment]
有个插件，叫做重命名增强的，现在还能用，但是不能批量改名，不知道能否给大神提供思路。另外，以前我改过一个相关插件（重命名文件）的代码，本来是不会改扩展名的，结果不知道怎么的我随便改了下代码，扩展名也改了。

重命名增强插件地址
 @namespace    https://greasyfork.org/scripts/447226
// @supportURL   https://gist.github.com/kunki/afc4e69df868266f3eb0ed02fcf0546a
// @homepageURL  https://gist.github.com/kunki/afc4e69df868266f3eb0ed02fcf0546a

**Comment by logxing** [comment]
3.7没改好 扩展名丢失了

**Comment by logxing** [comment]
> > 有一个方案可行，本地先删除文件名中所有的点字符. 这就去除了扩展名，传完后把点插入到倒数第四位。只不过其他位置的点就丢失了，除非你预先保存了所有的原始文件名。
> 
> 有些文件扩展名不止3位，比如分卷压缩文件，RMVB文件等。

对，那就稍微复杂点了，记录每一个文件的.的位置

**Comment by ForeverXXL** [comment]
那可不可以先加个带后缀的扩展名然后再删除呢,当然这个也容易被针对

**Comment by cjlzuiniub** [comment]
后缀名丢失，无法添加扩展名

**Comment by cjlzuiniub** [comment]
老哥，请问你是怎么加扩展名的呢，重命名的扩展都失效了。

**Comment by logxing** [comment]
其实可以将点替换为一个特殊字符，最后再换回点即可
当然原来的分隔符也是需要的

**Comment by Nerver4Ever** [comment]
关于后缀的问题，115调整接口中，等稳定了，我再尝试修改。。。

**Comment by logxing** [comment]
我去我知道怎么回事了，115在服务器端直接把你要改的目标文件名的扩展名部分去除了。比如你的文件是aaaa要改成bbbb.mp4，他最后会变成bbbb.     那个mp4是在服务器端去除的，也就是3.7的问题所在，貌似无解，因为你只能使用115提供的webapi。api里直接把最后一个点后面的部分舍弃了

**Comment by guyueyingmu** [comment]
> 关于后缀的问题，115调整接口中，等稳定了，我再尝试修改。。。

一种不需要依靠115接口的解决方案

以 abc.mp4 为例 

1. 转存时重复一遍扩展名: abc.mp4.mp4, 转存后变为 abc.mp4.
2. 在文件列表页面修改 html 标签参数, 将  `<ul><li iv="0" ` 改为 `<ul><li iv="1" ` 此时点击该文件会跳转播放页面

**Comment by leeonix** [comment]
> > 关于后缀的问题，115调整接口中，等稳定了，我再尝试修改。。。
> 
> 一种不需要依靠115接口的解决方案
> 
> 以 abc.mp4 为例
> 
> 1. 转存时重复一遍扩展名: abc.mp4.mp4, 转存后变为 abc.mp4.
> 2. 在文件列表页面修改 html 标签参数, 将  `<ul><li iv="0" ` 改为 `<ul><li iv="1" ` 此时点击该文件会跳转播放页面

我和你找到的方法类似。我是先重命名为abc.，限制后缀名为「.」，在重命名为abc.mp4，显示为abc.mp4. 
但刷新后，是可以播放的。我也试过下载下来，看上去是：「abc.mp4.」，但下载后没有后面的点是没有的，就是abc.mp4

**Comment by guyueyingmu** [comment]
> > > 关于后缀的问题，115调整接口中，等稳定了，我再尝试修改。。。
> > 
> > 
> > 一种不需要依靠115接口的解决方案
> > 以 abc.mp4 为例
> > 
> > 1. 转存时重复一遍扩展名: abc.mp4.mp4, 转存后变为 abc.mp4.
> > 2. 在文件列表页面修改 html 标签参数, 将  `<ul><li iv="0" ` 改为 `<ul><li iv="1" ` 此时点击该文件会跳转播放页面
> 
> 我和你找到的方法类似。我是先重命名为abc.，限制后缀名为「.」，在重命名为abc.mp4，显示为abc.mp4. 但刷新后，是可以播放的。我也试过下载下来，看上去是：「abc.mp4.」，但下载后没有后面的点是没有的，就是abc.mp4 也就是说。abc.mp4不行，但abp.mp4.是可以的。

我提交了pr  https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/pull/38
加一行代码以实现点后缀文件的播放, 如果是其他文件如压缩包,图片需要对比相应的参数再改过来

**Comment by muguou** [comment]
改了3个函数，没整理代码，写的比较粗糙，改了之后可以实现功能。原理就是把 . 替换成 "迡" 上传之后，再把 "迡" 换成 . 然后就可以用了

 async function processRenameByUsingHistory(files, separator, sleepTime, resultCallback) {

        let history = await getLastUploadFiles(files.length, sleepTime, t => {
            resultCallback({
                state: true,
                msg: t
            });
        });

        resultCallback({
            state: true,
            msg: "正在等待重命名...如果文件较多，请等待；或者停止，等以后手动操作去除分隔符。"
        });
        //fix: v3.3.1 修复含有重复文件的时候，未所有完成重命名的bug
        history.forEach(q => q.isMarked = false);
        for (const file of files) {
            //console.log("file")
            //console.log(file)
            let thisFile = history.find(q => q.sha1 == file.sha1 && q.parentID == file.parentID && q.name == file.formatedName && !q.isMarked);
            //console.log("thisFile")
            //console.log(thisFile)
            if (thisFile) {
                file.id = thisFile.id;
                thisFile.isMarked = true;
            } else {
                console.error(`历史记录里未找到 ${file.name}`);
            }
        }

        let selectedFiles = files.filter(f => f.formatedName.search(separator) != -1 && f.id).map(f => {
            //let lastIndex=f.formatedName.lastIndexOf(".");
            //let name=f.formatedName.substring(0,lastIndex);
            //let ext=f.formatedName.substring(lastIndex+1);

            let fo = {
                id: f.id,
                //fix
                //name: name.split(separator).join("")+"."+reverseString(ext)
                name: f.formatedName.split(separator).join("")    
            };
            return fo;
        });
        
        
        selectedFiles = selectedFiles.map(f => {
            //let lastIndex=f.name.lastIndexOf(".");
            //let name=f.name.substring(0,lastIndex);
            //let ext=f.name.substring(lastIndex+1);

            let fo = {
                id: f.id,
                //name: name.split(separator).join("")+"."+reverseString(ext)
                name:f.name.replace("迡" , ".")
            };
            return fo;
        });

        
        
        console.log(selectedFiles)
        let i, j, temporary, chunk = 115;
        for (i = 0, j = selectedFiles.length; i < j; i += chunk) {
            temporary = selectedFiles.slice(i, i + chunk);
            resultCallback && resultCallback({
                state: true,
                msg: `正在重命名第${i + 1}到${i + temporary.length}个文件...`
            });
            let renameResult = await renameFiles(temporary);
            if (renameResult.state === true) {
                resultCallback && resultCallback({
                    state: true,
                    msg: `重命名第${i + 1}到${i + temporary.length}个文件成功!`
                });
            } else {
                resultCallback && resultCallback({
                    state: false,
                    msg: renameResult.error
                });
                resultCallback && resultCallback({
                    state: true,
                    msg: `重命名第${i + 1}到${i + 1 + temporary.length}个文件中有失败！！!`
                });
            }
            await delay(sleepTime);
        }

    }



    async function processRename(targetFolderCid, separator, sleepTime, resultCallback) {
        let onlineFiles = new Array();
        await getAllFiles(targetFolderCid, onlineFiles, targetFolderCid, (fname, pIndex) => {
            if (pIndex > 1) {
                resultCallback && resultCallback({
                    state: true,
                    msg: `正在获取 【${fname}】 下第 ${pIndex} 页的内容...`
                });
            } else {
                resultCallback && resultCallback({
                    state: true,
                    msg: `正在获取 【${fname}】 下的内容...`
                });
            }
        });


        let selectedFiles = onlineFiles.filter(f => f.name.search(separator) != -1).map(f => {
            //let lastIndex=f.name.lastIndexOf(".");
            //let name=f.name.substring(0,lastIndex);
            //let ext=f.name.substring(lastIndex+1);

            let fo = {
                id: f.id,
                //name: name.split(separator).join("")+"."+reverseString(ext)
                name:f.name.split(separator).join("")
            };
            return fo;
        });


        selectedFiles = selectedFiles.map(f => {
            //let lastIndex=f.name.lastIndexOf(".");
            //let name=f.name.substring(0,lastIndex);
            //let ext=f.name.substring(lastIndex+1);

            let fo = {
                id: f.id,
                //name: name.split(separator).join("")+"."+reverseString(ext)
                name:f.name.replace("迡" , ".")
            };
            return fo;
        });



        let i, j, temporary, chunk = 115;
        for (i = 0, j = selectedFiles.length; i < j; i += chunk) {
            temporary = selectedFiles.slice(i, i + chunk);
            resultCallback && resultCallback({
                state: true,
                msg: `正在重命名第${i + 1}到${i + temporary.length}个文件...`
            });
            let renameResult = await renameFiles(temporary);
            if (renameResult.state === true) {
                resultCallback && resultCallback({
                    state: true,
                    msg: `重命名第${i + 1}到${i + temporary.length}个文件成功!`
                });
            } else {
                resultCallback && resultCallback({
                    state: false,
                    msg: renameResult.error
                });
                resultCallback && resultCallback({
                    state: true,
                    msg: `重命名第${i + 1}到${i + 1 + temporary.length}个文件中有失败！！!`
                });
            }
            await delay(sleepTime);
        }

    }


 //解析inline text sha1 links,并根据配置设置分隔符;返回FileArray
    function parseSha1LinksToFileArray(text, nameSeparator, errorCallback) {
        let textLines = text.split(/\r?\n/);

        let files = new Array();
        for (let line of textLines) {
            let fLine = line.trim();
            if (!fLine) continue;
            let r = convertFromSha1Link(fLine);
            if (r.state) {
                //let nameStrings = r.fileItem.name.split(".");
                //let extension = nameStrings.pop();
                //r.fileItem.extension = extension;
                //let formatedExtension=reverseString(extension);
                //根据配置重新设置文件名
                if (nameSeparator) {
                    //使用emoutils.js库来分割，带有emoji的文件名
                    //let fileName = emojiUtils.toArray(nameStrings.join('.')).map(c => c + nameSeparator).join("").slice(0, -1);
                    //r.fileItem.formatedName = fileName + "." + formatedExtension;
                    let newName = r.fileItem.name.split(".");
                    let newName2 =emojiUtils.toArray(newName[0]).map(c => c + nameSeparator).join("").slice(0, -1);
                    let newName3 = newName2 + "迡" + newName.pop();


                    //r.fileItem.formatedName=emojiUtils.toArray(r.fileItem.name).map(c => c + nameSeparator).join("").slice(0, -1);
                    r.fileItem.formatedName = newName3;

                } else {
                    r.fileItem.formatedName = r.fileItem.name;
                }
                files.push(r.fileItem);
            } else {
                errorCallback && errorCallback(`${fLine} 格式错误?`);
            }

        }

        return files;
    }

**Comment by sxq18** [comment]
测试了一下，如果只是把“.”改成生僻字，然后重命名回“.”，拓展名会丢失。

**Comment by Nerver4Ever** [comment]
@muguou   @guyueyingmu   
这两个方案我昨天试过，不一定都成功。
我有了新的方案。如果新方案不合适，再来考虑这两个。

**Comment by Hulk-Windows7** [comment]
笨方法就是用clouddrive来改后缀名

**Comment by ForeverXXL** [comment]
> @muguou @guyueyingmu 这两个方案我昨天试过，不一定都成功。 我有了新的方案。 如果新方案不合适，再来考虑这两个。

大佬说说什么方案呢,一起参考一下,我昨天试了一下电脑版本的115,发现是可以改后缀的,就是接口是pc的,可能验证加密什么的都要尝试

**Comment by lerenyx** [comment]
> 笨方法就是用clouddrive来改后缀名

cloud drive 已经失效了

**Comment by lerenyx** [comment]
> > @muguou @guyueyingmu 这两个方案我昨天试过，不一定都成功。 我有了新的方案。 如果新方案不合适，再来考虑这两个。
> 
> 大佬说说什么方案呢,一起参考一下,我昨天试了一下电脑版本的115,发现是可以改后缀的,就是接口是pc的,可能验证加密什么的都要尝试

PC 版 115 也失效了。。。

**Comment by ForeverXXL** [comment]
刚刚试了一下,pc也不行了

**Comment by ForeverXXL** [comment]
115这次太狠了!!

**Comment by jl0476** [comment]
> 笨方法就是用clouddrive来改后缀名

这个昨天可以，今天已经不行了。

**Comment by Hulk-Windows7** [comment]
> > 笨方法就是用clouddrive来改后缀名
> 
> 这个昨天可以，今天已经不行了。

今天失效了就可以在挂一个advanced namer

**Comment by logxing** [comment]
115疯了，cloud drive也改不了了

**Comment by jl0476** [comment]
> advanced namer


@Hulk-Windows7 这个是什么，现在Cloud Drive 改扩展名直接不生效了。

**Comment by iamtraceur** [comment]
> > advanced namer
> 
> @Hulk-Windows7 这个是什么，现在Cloud Drive 改扩展名直接不生效了。

这个只是一个快速改名的软件，用来在cloud driver挂载之后批量改名，现在cloud driver改名的办法失效了。不过这个软件用来改名还挺好用的

**Comment by jl0476** [comment]
哦 我都是用everything批量改名的

**Comment by EvansWu-1212** [comment]
写了一个小程序可以批量删除分隔符。
有需要可以下载：
https://github.com/EvansWu-1212/Rename_for_115

**Comment by logxing** [comment]
3.8.1版的去除分隔符功能怎么没了呢？这个还挺必要的啊，现在可以确保不会有去除不干净的情况了所以去掉这个功能了吗？

**Comment by Nerver4Ever** [comment]
@logxing 代码中搜索“类型匹配”自行添加。

手动去除分隔符，如果还有后续更新，会再上线

**Comment by logxing** [comment]
mp3 wma文件也发现有无法上传现象（文件名加间隔符也无法上传），但是如果扩展名是iso的话不少文件会出现转码提示，转码后可在平时的视频窗口界面播放。正常的音频文件点击后会自动在115的我听-临时歌单中播放，而且不需要转码，115歌单功能也无法添加iso后缀的文件。经测试追加其他常见音频文件扩展名均无法上传，目前没有找到类似iso对应视频这种对应音频文件的替代扩展名。音频文件一例（评书）115://000.mp3|5767168|0891E6622EE04D95EAEF81C3F676C34825B040EC|5C32A92D0A21BF84E43C74F3FF2DFDD6DEA183C3
