### ISSUE TITLE
建议readme文档不要写的太清晰

### ISSUE THREAD

**Issue by spartawhy117** [Nerver4Ever/SevenSha1UIAdvancedHelper#39]
115越来越严格的限制说明可能 官方已经知道这个脚本插件，他们也会去做对应的应对，不知道有没有混淆源代码还能正常安装的方式

**Comment by Nerver4Ever** [comment]
没有，他们抓包或者服务器上看一下日志，就很清楚啥情况。。

**Comment by iamtraceur** [comment]
> 没用，他们抓包或者服务器上看一下日志，就很清楚啥情况。。

大佬能不能提供一个不修改文件后缀名的版本，用来转存一些非和谐的东西，比如电视剧纪录片什么的

**Comment by metyouth** [comment]
大佬，这一关还有希望能过么，不行的话， 就得早点想招搬家了
