### ISSUE TITLE
一直卡在重命名不动

### ISSUE THREAD

**Issue by tb0668** [Nerver4Ever/SevenSha1UIAdvancedHelper#4]
一直卡在重命名不动

**Comment by Nerver4Ever** [comment]
正在定位问题。

可以用其他方法就行重命名：脚本设置中打开
![github](https://user-images.githubusercontent.com/85677288/167523987-eaf3a513-d1ec-4b8d-af63-6707f7c9b021.jpg)
然后文件夹上方悬浮条上进行”去除分隔符“操作；

如果没有嵌套文件夹，也可以用115自带的批量重命名。
