### ISSUE TITLE
更新之后找不到sha1按钮，最新版本v3.8.1 (143.2022.0818.2)

### ISSUE THREAD

**Issue by mako1024** [Nerver4Ever/SevenSha1UIAdvancedHelper#40]
**描述一下遇到的问题*
更新到最新版本v3.8.1 (143.2022.0818.2)
更新完之后刷新页面发现链接与任务那里没有sha1转存了，
退回旧版本重新再试也没有显示

**复现问题**
win10 115浏览器版本25.0.2.1
            油猴脚本v4.17.6161

**Comment by Nerver4Ever** [comment]
#32 
#20

**Comment by mako1024** [comment]
感谢大佬问题已解决了

**Comment by staynight055** [comment]
大佬我也遇到这个问题怎么办求解

**Comment by mako1024** [comment]
我的解决办法是把115浏览器退回到25.0之前的版本，网上搜都有，我自己的话是24.3.0.3的，还有就是检查一下油猴的版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月20日(周六) 凌晨0:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 更新之后找不到sha1按钮，最新版本v3.8.1 (143.2022.0818.2) (Issue #40)




 
大佬我也遇到这个问题怎么办求解

**Comment by staynight055** [comment]
我以前一直用的是Chrome最新版网页浏览的。可是现在不行了，网页版有办法吗

**Comment by mako1024** [comment]
现在除了115浏览器25.0之前的可以，我也是用Chrome的今晚试了不行，作者大佬原话:此版本目标：115浏览器端、115 ios app端能正常打开视频和图片，其他未测，也没有设备
建议您先下载115自己的浏览器试试看，而且还是25.0之前的版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月20日(周六) 凌晨0:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 更新之后找不到sha1按钮，最新版本v3.8.1 (143.2022.0818.2) (Issue #40)




 
我以前一直用的是Chrome最新版网页浏览的。可是现在不行了，网页版有办法吗

**Comment by Nerver4Ever** [comment]
几个追问的，是不是都不看文字啊= =！

#32 
有问题先搜索一遍！那怕网页下翻一点，就能看到一样的！
#20

**Comment by grdss1010** [comment]
> 追几个看问的，是不是没有文字啊= =！
> 
> [第32](https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/issues/32) 话有问题先搜索！ [第20话](https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/issues/20)

大佬，我现在的115版本和油猴版本都跟40楼楼主一样了，但我但用3.8还是不能显示转存按钮，换会3.6版就能正常显示，也试过好几个别人能正常用的115版本，但情况一样。我裂开了。

**Comment by WarpTraveller** [comment]
我之前遇到过类似问题。先把油猴插件删掉重装一下，再加入115脚本就OK了
