### ISSUE TITLE
115sha1按钮消失，退回原来助手版本也不显示

### ISSUE THREAD

**Issue by staynight055** [Nerver4Ever/SevenSha1UIAdvancedHelper#41]
浏览器是Chrome版本 104.0.5112.102（正式版本） （64 位）已经是最新版
转存助手是115转存助手ui优化版 v3.8.1(143.2022.0818.2).user 也是最新版
Tampermonkey  是4.16.1 版本
更新后sha1的转存按钮消失不显示 求大佬教教

**Comment by miss550** [comment]
我也是这样

**Comment by Nerver4Ever** [comment]
#40
