### ISSUE TITLE
为什么转存之后有一部分文件还是显示名字为J蠔U蠔Y蠔-蠔9蠔9蠔9蠔这种，有一部分就是这种名字，而且图片也打不开，只能下载

### ISSUE THREAD

**Issue by y2611629** [Nerver4Ever/SevenSha1UIAdvancedHelper#42]
**描述一下遇到的问题**
在此输入问题

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的

**Comment by y2611629** [comment]
补充一下 同一文件下有一部分是正常的文件名字 另一部分就是J蠔U蠔Y蠔-蠔9蠔9蠔9蠔这种，

**Comment by y2611629** [comment]
![image](https://user-images.githubusercontent.com/111592065/185671022-b3e949e6-6cd4-4d60-b150-8027bd24cd0d.png)

**Comment by staynight055** [comment]
大哥知道转存按钮不见了怎么解决吗我是chrome最新版网页

**Comment by Nerver4Ever** [comment]
最好附上sha1
