### ISSUE TITLE
用了3.8以后转存啥都 “等待上传结果超时，此乃警告！成功与否，看最后统计结果！”，然后转存失败

### ISSUE THREAD

**Issue by tsugumomo123** [Nerver4Ever/SevenSha1UIAdvancedHelper#44]
[**描述一下遇到的问题**](url)
在此输入问题

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. [附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的]

**Comment by Nerver4Ever** [comment]
大概率你的网络问题。。
