### ISSUE TITLE
图片显示为TIFF文件，无法在115网页端打开

### ISSUE THREAD

**Issue by y2611629** [Nerver4Ever/SevenSha1UIAdvancedHelper#45]
![image](https://user-images.githubusercontent.com/111592065/185726631-8c349297-4298-41f1-9efe-48dbcbb324ff.png)
ge格式为这种，打开就默认下载了，请问如何处理

**Comment by zxyvip** [comment]
mp4后缀为iso

**Comment by Nerver4Ever** [comment]
我这里可以，不知道你用的什么浏览器？或者附上图片sha1

**Comment by y2611629** [comment]
115://ADN-142 篠田ゆう あなた、許して…。-再会は淫らな嘘に濡れて-2 篠田ゆう 2017-11-18.jpg|149964|0FF20712458C5B07D06D7FC28ADAF9CA6A296666|824F2BDD84B752E359A17B600AE572DA7829E633|封面图
115://ANGR-005 篠田ゆう あなた見ないで ～牢獄の中の性玩具 篠田ゆう～ 2019-02-08.jpg|171875|74B1A487ECB646EA1E495F08018B9B5931999197|88966D5B8C4D7499A4445D8C2F7EBB71B19F686E|封面图
115://AQSH-024 篠田ゆう 夫の知らない淫らな愛妻 テニスサークルのコーチを連れ込んでヤリまくっているようなんです…。 篠田ゆう 2018-09-13.jpg|212095|C6F580984F4A97D1F1081C5127323027448A0965|4F894D38E0419B8A6A91D6B30AE22E35D500B46B|封面图
115://ATID-305 篠田ゆう 兄嫁レイプ 引きこもりの支配者 篠田ゆう 2018-08-04.jpg|188616|825974DC576BFDD39087C5F1A483EEB4897D3E04|1DFAFD8C3BA0B86854EC8E11F273D7C6CCBBFD43|封面图
115://ATID-397 篠田ゆう オフィスレディの湿ったパンスト 篠田ゆう 2020-02-01.jpg|150373|A4349C6DAE3FE8C85F7835AE2BA41C0458C0010F|AAE7DA8C733C777E56E17AD9CDE1A0B143E3A209|封面图
115://BF-522 篠田ゆう NTR 元カレに寝取られた同窓会 2017-09-30.jpg|152737|93610AA1B6214685A191C16D69FF5CBED7A12915|729D92BE01DE70896407F86298EBE26CF4D0D5F0|封面图
115://BF-540 篠田ゆう 部下を性教育するデカ尻女上司のバックで強制誘惑中出し！ 篠田ゆう 2018-04-13.jpg|145462|37AC1DF4865CC73FEFD790709AA7CD680C06D1B7|495CF690A9C34645E764BF77FA86F1431411A2EF|封面图
115://BF-551 篠田ゆう 透けピタパンツで誘惑する中出し家政婦 篠田ゆう 2018-09-07.jpg|155648|5AC59C83DC6CD94C51E5280642B000F1F33A9ACC|E78F1D9AD4AD2CF0CEAF7CB0F7BDF1A19921C43F|封面图
115://BONU-020 篠田ゆう ラブラブ痴女 閉じ込め淫語で限界がまん 篠田ゆう 2018-03-19.jpg|160031|80735D9F9E2081C91482791D8B2062D5B70D7936|220B5733CB9BA4DCF84EB9E7EDD14C179453C3FB|封面图
115://CESD-390 篠田ゆう アナルとマ○コを両方突かれたら気持ち良すぎてバカになっちゃう軟体尻穴SEX 篠田ゆう 2017-06-25.jpg|208826|78EE00D6A7C1BDC7559783F23AD97096EB66F13B|E77BCDCF4C5335C19B51D5905393C36FA33BC8DD|封面图
115://CESD-444 篠田ゆう,桐嶋りの 女同士のレズビアン姉貞愛 桐嶋りの 篠田ゆう 2017-09-18.jpg|201658|003DED49F6BB3DF99415FE63BBF4579B26C1C8C1|0FA570620A582F2B6AF0AAEE5D4D7BA4A9D64777|封面图
115://CJOD-124 篠田ゆう 凄い射精へ誘うケツ穴見せつけド迫力デカ尻オイルエステ 篠田ゆう 2017-12-30.jpg|168326|9714E8F35A22C5DF0DCEA609562358D70F1106D1|9637AA6FF57E04D61670FADCC9856C3F936F6B67|封面图
115://CJOD-138 篠田ゆう アナル丸見えデカ尻で亀頭ぐりぐり淫語たっぷりの焦らしスローピストン 篠田ゆう 2018-04-25.jpg|167193|CC55BA3DAABA2811179D11278CF5F13652C92775|3EDCE4989E6769196080D6E3CAD0958DB23FDFD5|封面图
115://CJOD-149 篠田ゆう,佐々波綾 W尻アナル丸見せ逆3P杭打ち中出し 篠田ゆう 佐々波綾 2018-07-21.jpg|193191|11565C5B99990AC70E6475B143FEEBDD54121965|F81C15DC6CA37AF8984248FD94EC4351CBF81BDC|封面图
115://CJOD-158 篠田ゆう キミも今日からデカ尻お姉さんの聖水便器 篠田ゆう 2018-09-25.jpg|176094|72D87A82E6DDE2556DF25B23B5ACDFECA1755C35|C39906DB11DEC8F4199998892449EF5EC85A48E5|封面图
115://CJOD-160 波多野結衣,大槻ひびき,篠田ゆう,武田真 絶対領域痴女ハーレム 美脚に挟まれ身動きできず中出しされちゃう！！ 2018-09-25.jpg|209752|F8546DD6508AB3DA1AA145B6157A6612B7D1C95E|1E02B8574D188EE06C002593878BA2D14B8AAA39|封面图
115://CJOD-163 篠田ゆう ぷるぷるデカ尻洗いが人気の銭湯のお姉さん 篠田ゆう 2018-10-21.jpg|173560|AC866A6FA02C6F62326EE3AE14A1A3DC84A42490|8108E97CA0611F4B527C49055A4C517366B12370|封面图
115://CJOD-183 篠田ゆう お義姉ちゃんのSEX練習に付き合っていたらまさかのゴム離脱！生チ○ポになった途端に仰け反り絶頂＆騎乗位が加速で暴発中出し！！ 篠田ゆう 2019-04-20.jpg|196002|5FA897E2F39DD907F9D5FED7985C9E67AF33D8E9|172CD17B5A4389BC616CA7DB99C618B9F5AAF6B5|封面图
115://CJOD-191 篠田ゆう 夢のドライオーガズム開発！乳首責めだけで何回もイッてみる？ 篠田ゆう 2019-06-22.jpg|192958|20EDFB65336FF688DAF69175E7F9D797EC690433|EF500B623BB45043669A32FB8EFD0F3E6F8C3D12|封面图

**Comment by y2611629** [comment]
这些下完就是显示后缀为.tiff 点击就是自动下载的状态

**Comment by y2611629** [comment]
用这些举个例子 还有其他类似情况

**Comment by MurderLee** [comment]
我也是这种情况

**Comment by suxss** [comment]
可以把代码第3636行改成

```javascript
                    r.fileItem.formatedExtension="";
```

不过这样有些文件会被和谐

---

代码第2962行好像是忘记把之前新加的后缀删了，

```javascript
            // let dataValue = value.name;
            // 改成
            let dataValue = changeNameBack(value.name);
```

这样改了之后重命名时发送的请求体是对的，但是还是没有用

比如原本要上传`001.jpg`，先重命名为`001.jpg.tiff`(忽略分隔符)，上传完后再发送请求，重命名为`001.jpg`，但是实际上会重命名为`001.tiff`，好像是因为115现在不允许改文件后缀

---
我了解的也不多，如果有问题，还请指正

**Comment by y2611629** [comment]
再补充一下，我用的是115浏览器

**Comment by y2611629** [comment]
是这两项都需要修改吗&nbsp; 还是只更改某一项？
&nbsp;


说你需要我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月21日(星期天) 凌晨1:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 图片显示为TIFF文件，无法在115网页端打开 (Issue #45)





 
可以把代码第3636行改成
                     r.fileItem.formatedExtension="";
 
不过这样有些文件会被和谐
 
 
代码第2962行好像是忘记把之前新加的后缀删了，
             // let dataValue = value.name;             // 改成             let dataValue = changeNameBack(value.name);
 
这样改了之后重命名时发送的请求体是对的，但是还是没有用
 
比如原本要上传001.jpg，先重命名为001.jpg.tiff(忽略分隔符)，上传完后再发送请求，重命名为001.jpg，但是实际上会重命名为001.tiff，好像是因为115现在不允许改文件后缀
 
 
我了解的也不多，如果有问题，还请指正

**Comment by y2611629** [comment]
老哥我按照你说的两种方法都试了 更改2962行的代码之后还是和以前一样&nbsp; 更改了3636行之后转存都不成功了 就会被和谐。不过还是多谢了




说你需要我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nerver4Ever/SevenSha1UIAdvancedHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 凌晨1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 图片显示为TIFF文件，无法在115网页端打开 (Issue #45)





 
可以把代码第3636行改成
                     r.fileItem.formatedExtension="";
 
不过这样有些文件会被和谐
 
 
代码第2962行好像是忘记把之前新加的后缀删了，
             // let dataValue = value.name;             // 改成             let dataValue = changeNameBack(value.name);
 
这样改了之后重命名时发送的请求体是对的，但是还是没有用
 
比如原本要上传001.jpg，先重命名为001.jpg.tiff(忽略分隔符)，上传完后再发送请求，重命名为001.jpg，但是实际上会重命名为001.tiff，好像是因为115现在不允许改文件后缀
 
 
我了解的也不多，如果有问题，还请指正

**Comment by y2611629** [comment]
恩 我下完的图片全是这种格式，都打不开 点开就是下载。
&nbsp;


说你需要我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月21日(星期天) 凌晨0:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 图片显示为TIFF文件，无法在115网页端打开 (Issue #45)





 
我也是这种情况

**Comment by y2611629** [comment]
115://ADN-142 篠田ゆう あなた、許して…。-再会は淫らな嘘に濡れて-2 篠田ゆう 2017-11-18.jpg|149964|0FF20712458C5B07D06D7FC28ADAF9CA6A296666|824F2BDD84B752E359A17B600AE572DA7829E633|封面图
115://ANGR-005 篠田ゆう あなた見ないで ～牢獄の中の性玩具 篠田ゆう～ 2019-02-08.jpg|171875|74B1A487ECB646EA1E495F08018B9B5931999197|88966D5B8C4D7499A4445D8C2F7EBB71B19F686E|封面图
115://AQSH-024 篠田ゆう 夫の知らない淫らな愛妻 テニスサークルのコーチを連れ込んでヤリまくっているようなんです…。 篠田ゆう 2018-09-13.jpg|212095|C6F580984F4A97D1F1081C5127323027448A0965|4F894D38E0419B8A6A91D6B30AE22E35D500B46B|封面图
115://ATID-305 篠田ゆう 兄嫁レイプ 引きこもりの支配者 篠田ゆう 2018-08-04.jpg|188616|825974DC576BFDD39087C5F1A483EEB4897D3E04|1DFAFD8C3BA0B86854EC8E11F273D7C6CCBBFD43|封面图
115://ATID-397 篠田ゆう オフィスレディの湿ったパンスト 篠田ゆう 2020-02-01.jpg|150373|A4349C6DAE3FE8C85F7835AE2BA41C0458C0010F|AAE7DA8C733C777E56E17AD9CDE1A0B143E3A209|封面图
115://BF-522 篠田ゆう NTR 元カレに寝取られた同窓会 2017-09-30.jpg|152737|93610AA1B6214685A191C16D69FF5CBED7A12915|729D92BE01DE70896407F86298EBE26CF4D0D5F0|封面图
115://BF-540 篠田ゆう 部下を性教育するデカ尻女上司のバックで強制誘惑中出し！ 篠田ゆう 2018-04-13.jpg|145462|37AC1DF4865CC73FEFD790709AA7CD680C06D1B7|495CF690A9C34645E764BF77FA86F1431411A2EF|封面图
115://BF-551 篠田ゆう 透けピタパンツで誘惑する中出し家政婦 篠田ゆう 2018-09-07.jpg|155648|5AC59C83DC6CD94C51E5280642B000F1F33A9ACC|E78F1D9AD4AD2CF0CEAF7CB0F7BDF1A19921C43F|封面图
115://BONU-020 篠田ゆう ラブラブ痴女 閉じ込め淫語で限界がまん 篠田ゆう 2018-03-19.jpg|160031|80735D9F9E2081C91482791D8B2062D5B70D7936|220B5733CB9BA4DCF84EB9E7EDD14C179453C3FB|封面图
115://CESD-390 篠田ゆう アナルとマ○コを両方突かれたら気持ち良すぎてバカになっちゃう軟体尻穴SEX 篠田ゆう 2017-06-25.jpg|208826|78EE00D6A7C1BDC7559783F23AD97096EB66F13B|E77BCDCF4C5335C19B51D5905393C36FA33BC8DD|封面图
115://CESD-444 篠田ゆう,桐嶋りの 女同士のレズビアン姉貞愛 桐嶋りの 篠田ゆう 2017-09-18.jpg|201658|003DED49F6BB3DF99415FE63BBF4579B26C1C8C1|0FA570620A582F2B6AF0AAEE5D4D7BA4A9D64777|封面图
115://CJOD-124 篠田ゆう 凄い射精へ誘うケツ穴見せつけド迫力デカ尻オイルエステ 篠田ゆう 2017-12-30.jpg|168326|9714E8F35A22C5DF0DCEA609562358D70F1106D1|9637AA6FF57E04D61670FADCC9856C3F936F6B67|封面图
115://CJOD-138 篠田ゆう アナル丸見えデカ尻で亀頭ぐりぐり淫語たっぷりの焦らしスローピストン 篠田ゆう 2018-04-25.jpg|167193|CC55BA3DAABA2811179D11278CF5F13652C92775|3EDCE4989E6769196080D6E3CAD0958DB23FDFD5|封面图
115://CJOD-149 篠田ゆう,佐々波綾 W尻アナル丸見せ逆3P杭打ち中出し 篠田ゆう 佐々波綾 2018-07-21.jpg|193191|11565C5B99990AC70E6475B143FEEBDD54121965|F81C15DC6CA37AF8984248FD94EC4351CBF81BDC|封面图
115://CJOD-158 篠田ゆう キミも今日からデカ尻お姉さんの聖水便器 篠田ゆう 2018-09-25.jpg|176094|72D87A82E6DDE2556DF25B23B5ACDFECA1755C35|C39906DB11DEC8F4199998892449EF5EC85A48E5|封面图
115://CJOD-160 波多野結衣,大槻ひびき,篠田ゆう,武田真 絶対領域痴女ハーレム 美脚に挟まれ身動きできず中出しされちゃう！！ 2018-09-25.jpg|209752|F8546DD6508AB3DA1AA145B6157A6612B7D1C95E|1E02B8574D188EE06C002593878BA2D14B8AAA39|封面图
115://CJOD-163 篠田ゆう ぷるぷるデカ尻洗いが人気の銭湯のお姉さん 篠田ゆう 2018-10-21.jpg|173560|AC866A6FA02C6F62326EE3AE14A1A3DC84A42490|8108E97CA0611F4B527C49055A4C517366B12370|封面图
115://CJOD-183 篠田ゆう お義姉ちゃんのSEX練習に付き合っていたらまさかのゴム離脱！生チ○ポになった途端に仰け反り絶頂＆騎乗位が加速で暴発中出し！！ 篠田ゆう 2019-04-20.jpg|196002|5FA897E2F39DD907F9D5FED7985C9E67AF33D8E9|172CD17B5A4389BC616CA7DB99C618B9F5AAF6B5|封面图
115://CJOD-191 篠田ゆう 夢のドライオーガズム開発！乳首責めだけで何回もイッてみる？ 篠田ゆう 2019-06-22.jpg|192958|20EDFB65336FF688DAF69175E7F9D797EC690433|EF500B623BB45043669A32FB8EFD0F3E6F8C3D12|封面图


随便选取了一些115sha1 下完全是显示后缀为tiff 点击就是自动下载，浏览器是115浏览器，希望大佬查看一下有什么解决方案




说你需要我
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nerver4Ever/SevenSha1UIAdvancedHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月20日(星期六) 晚上9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 图片显示为TIFF文件，无法在115网页端打开 (Issue #45)





 
我这里可以，不知道你用的什么浏览器？或者附上图片sha1

**Comment by suxss** [comment]
> 老哥我按照你说的两种方法都试了 更改2962行的代码之后还是和以前一样&nbsp; 更改了3636行之后转存都不成功了 就会被和谐。不过还是多谢了 说你需要我 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nerver4Ever/SevenSha1UIAdvancedHelper" ***@***.***&gt;; 发送时间:&nbsp;2022年8月21日(星期天) 凌晨1:02 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 图片显示为TIFF文件，无法在115网页端打开 (Issue #45) 可以把代码第3636行改成 r.fileItem.formatedExtension=""; 不过这样有些文件会被和谐 代码第2962行好像是忘记把之前新加的后缀删了， // let dataValue = value.name; // 改成 let dataValue = changeNameBack(value.name); 这样改了之后重命名时发送的请求体是对的，但是还是没有用 比如原本要上传001.jpg，先重命名为001.jpg.tiff(忽略分隔符)，上传完后再发送请求，重命名为001.jpg，但是实际上会重命名为001.tiff，好像是因为115现在不允许改文件后缀 我了解的也不多，如果有问题，还请指正 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

现在115改了，上传的时候如果改后缀，上传完了之后没法改回来，所以改第二处没用，如果不改后缀，像jpg、png、gif这些能在线看的格式在审核的时候不只审核文件名，所以改第一处有些文件会被和谐
#37  这个issue里面提到了类似的问题
