### ISSUE TITLE
视频及图片的后缀名被修改

### ISSUE THREAD

**Issue by ZeLye** [Nerver4Ever/SevenSha1UIAdvancedHelper#46]
**描述一下遇到的问题**
视频添加了一个.iso的后缀名，
图片添加了一个.tiff的后缀名。
例如原文件名为XXX.mp4转存后变为XXX.mp4.iso

脚本与环境信息： [gm]:Tampermonkey [gmVersion]:4.16.1 [ua]:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 [version]:143.2022.0818.2

**Comment by logxing** [comment]
老兄，你是新新新新新来的吧。。。

**Comment by ZeLye** [comment]
> 

什么意思？
