### ISSUE TITLE
更新至3.8.1不显示获取SHA1按钮了

### ISSUE THREAD

**Issue by lonlycar** [Nerver4Ever/SevenSha1UIAdvancedHelper#47]
**描述一下遇到的问题**
在此输入问题
更新至3.8.1不显示获取SHA1按钮了
**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的
![image](https://user-images.githubusercontent.com/34016829/185731506-2fce69c6-5538-44e9-ab6e-049866f3ae4b.png)
![image](https://user-images.githubusercontent.com/34016829/185731561-6da4101b-e73f-4a6d-be27-73bb1dd2c707.png)

**Comment by AriKing11** [comment]
我也是 而且用以前的老版本也不显示了

**Comment by Nerver4Ever** [comment]
#32 
有问题先搜索一遍！那怕网页下翻一点，就能看到一样的！
#20
