### ISSUE TITLE
能不能在UI上加一个设置开关决定是否追加扩展名

### ISSUE THREAD

**Issue by logxing** [Nerver4Ever/SevenSha1UIAdvancedHelper#48]
有些MP4，jpg文件仅仅插入字符是可以成功上传的（但是不插入字符无法成功上传）。此时不想无谓的追加iso等扩展名。如果ui上可以选择关闭追加扩展名就好了

**Comment by Nerver4Ever** [comment]
后续有时间可以安排

**Comment by zhouLife** [comment]
确实还是喜欢MP4 修改iso后缀并不影响它要封你
