### ISSUE TITLE
频繁请求，被115限制 (尝试停止操作半小时或者重新登录)，一直出现这个错误

### ISSUE THREAD

**Issue by wuyuehai98** [Nerver4Ever/SevenSha1UIAdvancedHelper#49]
**描述一下遇到的问题**
在此输入问题
上传遇到致命错误，已主动停止！频繁请求，被115限制 (尝试停止操作半小时或者重新登录)，
一直报这个错误，等了半小时或者重新登陆也没办法解决
**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的
![115截图20220820225429](https://user-images.githubusercontent.com/40877844/185752717-586f1997-acf9-4dee-b0fa-91bf33d31e3f.png)

**Comment by Nerver4Ever** [comment]
高峰期，容易被限制，正常。。。

**Comment by wuyuehai98** [comment]
> 

大佬，那是要到白天或者深夜来弄就可能转存成功了是吗？？
