### ISSUE TITLE
升级v3.5版本  点开链接按钮以后 不显示转存按钮，具体看图。 

### ISSUE THREAD

**Issue by youthyan** [Nerver4Ever/SevenSha1UIAdvancedHelper#5]
问题：
 v3.5版本  点开链接按钮以后  
 里面不显示sha1转存 按钮，
但是降级到 v3.0 却显示转存按钮。

环境：
mac os 11.6.4（intel ）
谷歌浏览器 和115浏览器 
都反复测试过  好几遍
 
油猴版本 v4.16.1
115转存助手ui优化版 最新版   -   版本 143.2021.0911.1

截图

v3.0显示转存按钮 

<img width="963" alt="截屏2022-05-11 下午11 23 42" src="https://user-images.githubusercontent.com/105373147/167887571-9b4eb439-9976-4f88-829a-c9d46b2d4d98.png">

但是升级后 
----v3.5 不显示转存按钮 
<img width="873" alt="截屏2022-05-11 下午11 08 53" src="https://user-images.githubusercontent.com/105373147/167884487-02be3d7e-9c0c-43f3-828c-6ddd59423040.png">

F12，cosnole页面，红色的报错的
（1）
<img width="626" alt="截屏2022-05-11 下午11 16 16" src="https://user-images.githubusercontent.com/105373147/167886702-957dcffc-02f9-426b-ba78-27ab22cd442e.png">
（2）
<img width="585" alt="截屏2022-05-11 下午11 16 44" src="https://user-images.githubusercontent.com/105373147/167886767-7439e286-04c3-4891-9455-ac4e96523276.png">
（3）
<img width="592" alt="截屏2022-05-11 下午11 16 58 1" src="https://user-images.githubusercontent.com/105373147/167886849-efb9cddd-0cd8-4a31-9f27-5f5e27ad0871.png">
（4）
<img width="597" alt="截屏2022-05-11 下午11 17 09" src="https://user-images.githubusercontent.com/105373147/167886927-ae91b874-bbe7-4070-b6db-e0aee4552faa.png">
（5）
<img width="626" alt="截屏2022-05-11 下午11 17 22" src="https://user-images.githubusercontent.com/105373147/167886977-112f615f-66c7-4eb6-a430-4548f6465b57.png">
 多截了几张图

**Comment by Nerver4Ever** [comment]
你的网络或者浏览器对一下依赖库可能进行屏蔽。你可以逐个访问试试。

https://unpkg.zhimg.com/underscore@1.12.0/underscore-min.js
 https://unpkg.zhimg.com/sweetalert2@11.3.0
 https://unpkg.zhimg.com/node-forge@0.10.0/dist/forge.min.js
 https://unpkg.zhimg.com/emoutils@2.0.0/dist/umd/emoutils.min.js

**Comment by Nerver4Ever** [comment]
挂vpn，或者将以上国内镜像地址改为原来地址。部分地区国内镜像不能访问了，但是国外cdn又可以访问了。
代码中开头几个改为如下

https://unpkg.com/underscore@1.12.0/underscore-min.js
https://unpkg.com/sweetalert2@11.3.0
https://unpkg.com/node-forge@0.10.0/dist/forge.min.js
https://unpkg.com/emoutils@2.0.0/dist/umd/emoutils.min.js
