### ISSUE TITLE
最新版本v3.8.1 控制台疯狂报错

### ISSUE THREAD

**Issue by yao00jun** [Nerver4Ever/SevenSha1UIAdvancedHelper#50]
**描述一下遇到的问题**
最新版本v3.8.1 控制台疯狂报错，开头的4个js文件，单独访问都是OK的，应该不是网络问题。

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

        [gm]:Tampermonkey
       [gmVersion]:4.16.1
       [ua]:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 115Browser/25.0.2.1
       [version]:143.2022.0818.2

**截图**
![image](https://user-images.githubusercontent.com/2508468/185756550-4691eabd-3dbd-4c6b-91f5-1806a5a8e989.png)
![image](https://user-images.githubusercontent.com/2508468/185756568-87ab1a23-2aa1-4add-92cc-2f90412ac709.png)
![image](https://user-images.githubusercontent.com/2508468/185756579-d074cdd1-8d15-4585-8061-e9d45b0f95f3.png)

**Comment by Nerver4Ever** [comment]
能正常使用吗？
第一张报错是115自己的问题。
不行就切换网络，或者重装脚本再尝试

**Comment by hackcraker** [comment]
使用不了

不停的在报错，按钮也没有
