### ISSUE TITLE
#38.1视频文件被和谐

### ISSUE THREAD

**Issue by lite118** [Nerver4Ever/SevenSha1UIAdvancedHelper#52]
刚发现文件下载时候，四千多个文件，成功四千左右之后然后开始被和谐，之后试了一个之前转存成功的，图片转存成功了但是视频全被和谐了，是不是又被官方安排了

**Comment by EnnawYang** [comment]
是的，115程序員上班了

**Comment by a393767577** [comment]
这速度是不是专门有人盯着呢
