### ISSUE TITLE
3.8.1版本，iso结尾的文件已经被河蟹无法上传，还有后缀播放问题。

### ISSUE THREAD

**Issue by cjlzuiniub** [Nerver4Ever/SevenSha1UIAdvancedHelper#54]
今天中午开始，ISO结尾已经无法上传了，和正常后缀名一样被全部河蟹。
还有也是今天中午开始以点结尾的文件也无法调用115的播放器播放，提示为“文件扩展名不正确无法播放”。
看来115是想通过后缀名堵在线播放这条路。

**通过几次更新知道115的人一直在盯着，就吐槽一下，115的程序猿咋都是中午修bug，中午不休息的吗。**

**Comment by tonydlut** [comment]
我这儿也遇到了同样的问题，昨天晚上是好用的，今天下午试了一下版本v3.8.1(143.2022.08182)中的ISO照样会被河蟹。

**Comment by cwinl** [comment]
我也遇到.iso被河蟹的问题
只能改名了
我这样做的：
替换名字   .mp4  或 .mp4.iso  都替换为其他字符，比如  win,  这样文件就没有 mp4名字，也不能在线播
然后每次只填10个左右的文件，不要一次太多

这样我把全部都能sha1进去
下载后再自己改名吧

别人有更好的办法吗？

**Comment by lerenyx** [comment]
> 

是的，现在不是在线问题了，是直接连文件都拿不到

**Comment by cjlzuiniub** [comment]
玩完了啊，这是。
一开始把bt弄了，现在又把sha1去了。
那么高的会员费，就变成单机了，用个毛线。
