### ISSUE TITLE
额 基本上违规的都传不上去了， 不只是后缀名的问题了，完全传不上了。

### ISSUE THREAD

**Issue by lonlycar** [Nerver4Ever/SevenSha1UIAdvancedHelper#55]
**描述一下遇到的问题**
在此输入问题

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的

**Comment by cjlzuiniub** [comment]
对滴，彻底玩完了

**Comment by exp4sky** [comment]
sha1 彻底完了
