### ISSUE TITLE
一个极其怪异的实例，相同的文件不同名字，一个成功一个失败

### ISSUE THREAD

**Issue by logxing** [Nerver4Ever/SevenSha1UIAdvancedHelper#58]
115://22 击坠王，小当家是下一个目标.mkv|549556107|07D03CFD3271FEC08C25B29B7DB29040901F3405|F5885747FDA01AAABACFB38A625FD5BE826D71CF
115://小当家.mkv|549556107|07D03CFD3271FEC08C25B29B7DB29040901F3405|F5885747FDA01AAABACFB38A625FD5BE826D71CF

上传时关闭自动添加分隔符。也不追加扩展名

最怪异的是：22 击坠王，小当家是下一个目标.mkv这个是成功上传的，而小当家.mkv，甚至你改成小当家没有扩展名都是违规的。
这里面的逻辑是什么，对规避违规有什么启发呢？在特定名字下违规文件也可以成功，这个特定的名字是什么？

同样性质的文件还有一个
115://24 神秘邀请函，面具厨师的陷井.mkv|552529722|B978B2E4D2C596A3116ADD8042577CB531A4221C|35565D8A96A961FF07C29B55B93F22B18B6426D8

可以成功，但文件名改成陷阱.mkv，反而违规了。

**Comment by a393767577** [comment]
正规资源都不行了

**Comment by metyouth** [comment]
特征码违规的你改啥名也没用

**Comment by logxing** [comment]
> 特征码违规的你改啥名也没用

就我例子里这个文件，不告诉那个成功的名字的话，你不也以为是特征码违规吗？

**Comment by exp4sky** [comment]
问了客服说大会过会就好了。希望如此把

**Comment by yishiyishi** [comment]
> 

是最近要开的网络文明大会吗，还是二十大

**Comment by Afinale** [comment]
真的吗，客服这么说？

**Comment by iamtraceur** [comment]
我建议大家暂时还是不要再公开讨论了，现在已经这样了，多说也无益。不论真假，就此打住，各退一步，不要再苦苦相逼了。我们在这里非要刨根问题说个清楚，对方就算想睁只眼闭只眼都不行了。
