### ISSUE TITLE
請教一下，115秒傳鏈接後面有兩個40位的值，一個是文件的sha1值，另一個是什麼？

### ISSUE THREAD

**Issue by luchenhao** [Nerver4Ever/SevenSha1UIAdvancedHelper#6]
115://爱否画质测试.mp4|1116990865|923FBC25814FDD2C39E7D15D0D46E5BFD9B63E69|489774D7F9E3C3F0041013B13F5227287241E11D

請教一下，中間40位是sha1,前面和後面的值是什麼？
知道文件名和sha1值能不能生成這樣的鏈接？

**Comment by Nerver4Ever** [comment]
文件内容前128KB的sha1
