### ISSUE TITLE
115好像活了？

### ISSUE THREAD

**Issue by lydygg** [Nerver4Ever/SevenSha1UIAdvancedHelper#61]
亲测直接拖拽文件部分可用，3.81基本100%成功但是后缀名略有瑕疵

**Comment by exp4sky** [comment]
是的，我也刚测试了。这一块yiyi5绝对是王者

**Comment by vbtyty** [comment]
目前能用，继续支持。

**Comment by vbtyty** [comment]
115本身离线也可以，目前主要是违规文件较多，没法上传了。另外有些文件能秒传转存，但是不能分享了。

**Comment by bili-jing** [comment]
为啥3.8.1的我这边没有转存按钮的。
![image](https://user-images.githubusercontent.com/45563478/192140106-b8410aa1-6611-4af1-a0bb-8f77af9e0d56.png)
有大佬知道么

**Comment by wingpro** [comment]
> 为啥3.8.1的我这边没有转存按钮的。
> ![image](https://user-images.githubusercontent.com/45563478/192140106-b8410aa1-6611-4af1-a0bb-8f77af9e0d56.png)
> 有大佬知道么

我也是，没有这个按钮，求大佬解惑。

**Comment by Vermoudol** [comment]
上面的，我也是没有转存按钮0.0
