### ISSUE TITLE
可以把iso、tiff批量转换为正常格式吗

### ISSUE THREAD

**Issue by BrunuhVille** [Nerver4Ever/SevenSha1UIAdvancedHelper#63]
115昨天开始复活了，视频不需要用iso后缀了，图片也不需要用tiff了
之前的iso、tiff后缀可以批量转换为正常的视频、图片格式吗
比如当前目录下的，或者某一目录下的
感谢大佬

**Comment by okaygh** [comment]
用3.6版试了试,好像只是放松了屏蔽,但是改后缀还是封掉了,不加ISO后缀没法在线看

**Comment by wwwwww1111** [comment]
建议增加选项，仅针对文件名加屏蔽字，扩展名保持不变

**Comment by Nerver4Ever** [comment]
退回老版本使用。。。
