### ISSUE TITLE
v3.8.1上传SHA1报错：可能参数不正确(?)：请升级到最新版本

### ISSUE THREAD

**Issue by Xingeqwd** [Nerver4Ever/SevenSha1UIAdvancedHelper#65]
**描述一下遇到的问题**

v3.8.1报错：可能参数不正确(?)：请升级到最新版本，然而Chrome(v105)，Tampermonkey(v4.16)与脚本(v3.8.1)都是最新版（截至目前）

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
```
115://浪潮之巅第4版.吴军.pdf|9155421|9F204F996CFDE3E5B5125EFC9BCCE928866F4C1E|6D11CAAC5541E382202799CE8F3881E8D0CC06DC
115://非烟3-40.7z|5983|B944AE68E6D59C023DD9B74F34D4385BB11786A6|B944AE68E6D59C023DD9B74F34D4385BB11786A6
（比较有代表性的两个链接）
```
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”
`[gm]:Tampermonkey [gmVersion]:4.16.1 [ua]:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 [version]:143.2022.0818.2`

**截图**
1.如有可能附上提示出错截图
![image](https://user-images.githubusercontent.com/46107662/192687649-11fb93e9-3e44-4d62-b056-63240dc53e7e.png)
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的
![image](https://user-images.githubusercontent.com/46107662/192687739-f23dc7b8-dd7c-4f59-91f5-960bc16519bf.png)

**Comment by Xingeqwd** [comment]
咳咳，怀疑可能是脚本被115封了吧（毕竟issue方面的二三十位同志都是这样），还特别换了浏览器（换成了firefox），结果依旧

开发人员辛苦了！不容易啊

**Comment by lzwzhx** [comment]
开发者辛苦了，115又封shi1了

**Comment by yiyangxian** [comment]
是了，开发者辛苦了
