### ISSUE TITLE
更新到了V3.8.1版本转存的时候提示：可能参数不正确

### ISSUE THREAD

**Issue by xiangli16** [Nerver4Ever/SevenSha1UIAdvancedHelper#66]
脚本更新到了V3.8.1版本，浏览器版本25.0.4.1，转存的时候提示：可能参数不正确(?)：请升级到最新版本。
转存失败

**Comment by lzwzhx** [comment]
都不能用了

**Comment by yiyangxian** [comment]
是了，我的我的提示是升级到最新版本，不会端了吧

**Comment by lzwzhx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
  祝你新年快乐 初8以后才能发布歌曲、video、种子
[imge]http://yomqrg.blu.livefilestore.com/y1papk1FbGRRQtUnXkJVDdRglcp8MhgreJmVbAoq_2x-dgxxYyTyQNCE7IZWcHtorRwB8-t2aTNi71bMbas0OjU8ndvTwFvIBHg/%E8%99%8E%E5%B9%B4%E5%90%89%E7%A5%A5.jpg[/imge]

**Comment by hunter8605** [comment]
遇到同样问题的来报道

**Comment by Yodamt** [comment]
+1

**Comment by langruohuitou** [comment]
+1
