### ISSUE TITLE
3.6b版本转存助手，附件发你了

### ISSUE THREAD

**Issue by meituan007** [Nerver4Ever/SevenSha1UIAdvancedHelper#70]
3.6b版本转存助手，附件发你了
修改文件扩展名为“js"

水纹の光牙
***@***.***

&nbsp;

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nerver4Ever/SevenSha1UIAdvancedHelper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月6日(星期四) 中午1:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nerver4Ever/SevenSha1UIAdvancedHelper] 转存时提示：可能参数不正确(?)：请升级到最新版本 (Issue #67)

 
我降到了3.6版本, 还是不行.
 "请升级到最新版本"这个string是从哪来的, 感觉好像是从某个引用的库里抛出来的信息.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

_Originally posted by @skgpx in https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/issues/67#issuecomment-1272226883_

**Comment by meituan007** [comment]
meituan007@gmail.com 可以分享一下吗

**Comment by hua189** [comment]
355903902@qq.com  可以分享一下吗

**Comment by FRXXZGZR** [comment]
626655233@qq.com可以分享一下吗？

**Comment by ec3800** [comment]
hujie_fan@126.com可以分享一下么，谢谢

**Comment by WzLaruku** [comment]
请分享下40622767@qq.com, 谢谢。

**Comment by shawnfun8144** [comment]
82042407@qq.com，可以分享一下么，谢谢了！！！

**Comment by DANGDANG1122** [comment]
408940246@qq.com,请分享一下，谢谢
