### ISSUE TITLE
V3.6和V3.8.1生成或转存文件都失败，出现时间北京时间10月16日凌晨3点至今

### ISSUE THREAD

**Issue by tkx15816072342** [Nerver4Ever/SevenSha1UIAdvancedHelper#71]
**描述一下遇到的问题**
在此输入问题
生成时提醒：很抱歉，提取码不能为空。
![image](https://user-images.githubusercontent.com/115137742/196026620-50c54002-60f8-43ad-966c-d16c6059b43a.png)
转存时提醒：上传失败。
![image](https://user-images.githubusercontent.com/115137742/196026653-6785b0ae-bc0e-4a61-b624-da68e892a4e0.png)
V3.6和V3.8.1生成或转存文件都失败，出现时间北京时间10月16日凌晨3点至今

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的

**Comment by stanosaka** [comment]
遇到相同问题，使用澳大利亚ip

**Comment by acollegebaby** [comment]
> Reference

国内的不行吧，老哥

**Comment by TonyLinGit** [comment]
> 

我人在泰国也不行。。。

**Comment by acollegebaby** [comment]
> 使用国内IP

老哥，导出的问题你那边解决了吗， 解决的话麻烦提供一下方法
