### ISSUE TITLE
点击“开始sha1转存”按钮后，就一直转圈 ，显示“正在操作中”

### ISSUE THREAD

**Issue by zqtljs** [Nerver4Ever/SevenSha1UIAdvancedHelper#72]
**描述一下遇到的问题**
点击“开始sha1转存”按钮后，就一直转圈 ，显示“正在操作中”
版本V3.8.1，浏览器Chrome

![截屏2022-10-21 22 30 25](https://user-images.githubusercontent.com/12293967/197222276-08f65a4c-c565-4554-af4d-a83885b5c22b.png)

**Comment by Steven-Zhl** [comment]
不如试试v3.6吧，我在3.6版本可以正常转存

https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/raw/90873e11657412cd07f01985bf1aa26c917e9705/115%E8%BD%AC%E5%AD%98%E5%8A%A9%E6%89%8Bui%E4%BC%98%E5%8C%96%E7%89%88.user.js

**Comment by zqtljs** [comment]
> 不如试试v3.6吧，我可​​以在3.6版本正常转存
> 
> [https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/raw/90873e11657412cd07f01985bf1aa26c917e9705/115%E8%BD%AC%E5%AD%98%E5%8A%A9%E6%89%8Bui%E4%BC%98%E5% 8C%96%E7%89%88.user.js](https://github.com/Nerver4Ever/SevenSha1UIAdvancedHelper/raw/90873e11657412cd07f01985bf1aa26c917e9705/115%E8%BD%AC%E5%AD%98%E5%8A%A9%E6%89%8Bui%E4%BC%98%E5%8C%96%E7%89%88.user.js)

谢谢

**Comment by peteryan612** [comment]
我也是相同的状况，请问问题解决了吗
