### ISSUE TITLE
V3.6和V3.8.1都出现转存上传失败问题

### ISSUE THREAD

**Issue by Bourkest** [Nerver4Ever/SevenSha1UIAdvancedHelper#73]
浏览器Chrome 版本V3.8.1, 3.5, 3.6都试过 
昨天开始出现此状况 海外IP 求教

**Comment by TonyLinGit** [comment]
一样。。。我也有同样的问题。现在 填入115连接，直接点了 转存 按钮后，弹框都没了。。。。
