### ISSUE TITLE
必须要用VPN选择国内模式才能正常使用3.6版本，其他版本不能用

### ISSUE THREAD

**Issue by mylongdays** [Nerver4Ever/SevenSha1UIAdvancedHelper#74]
想问下有没有跟我一样的，只有3.6版本还能用，而且是关掉VPN不能用，VPN选择翻墙模式也不能用，必须打开VPN后选择回国模式才可以转存成功，否则其他情况全部都是参数不正确。

**Comment by z354336675** [comment]
> 想问下有没有跟我一样的，只有3.6版本还能用，而且是关掉VPN不能用，VPN选择翻墙模式也不能用，必须打开VPN后选择回国模式才可以转存成功，否则其他情况全部都是参数不正确。

这样居然能用？

**Comment by mylongdays** [comment]
> 

就是因为我自己都觉得离谱所以才来问问有没有跟我一样的情况。

**Comment by tkx15816072342** [comment]
> > 想问下有没有跟我一样的，只有3.6版本还能用，而且是关掉VPN不能用，VPN选择翻墙模式也不能用，必须打开VPN后选择回国模式才可以转存成功，否则其他情况全部都是参数不正确。
> 
> 这样居然能用？
嗯，同在国外，20大期间必须翻墙回国用国内的ip才能正常保存
现在已经不用这样了，直接存就行

**Comment by Jihad0893** [comment]
看了下console报错，试了几个版本，3.6/3.8都有，应该是forge这个库用的源不行，导致需要先执行的全部没执行，然后就后面全部卡住了。试着3.6版改了个源就能用了，懂的话目前改的这个可以用npm.elemecdn.com

**Comment by xzm2000** [comment]
> 看了下console报错，试了几个版本，3.6/3.8都有，应该是引用库用的源不行，导致需要先执行的全部没执行，然后就后面全部卡住了；甚至试着转存也是这些库用不了又卡住。试着3.6版全部改了个源就能用了，懂的话目前改的这个可以用npm.elemecdn.com

我这边控制台显示是没有emojiUtil那个库……不知道是不是没加载出来
