### ISSUE TITLE
转存的时候一直卡在正在操作中转圈圈，一晚上也没有变化

### ISSUE THREAD

**Issue by peteryan612** [Nerver4Ever/SevenSha1UIAdvancedHelper#75]
**描述一下遇到的问题**
转存的时候一直卡在正在操作中转圈圈，一晚上也没有变化
是哪里出的问题呀，第一次使用转存
**截图**
![QQ图片20221031135504](https://user-images.githubusercontent.com/117060664/198958819-e3707202-cf44-4983-a17a-afae77b393f8.png)

**Comment by tkx15816072342** [comment]
刷新再来一次就可以了
不行的话再刷新重来
