### ISSUE TITLE
3.6可用  最新用不了

### ISSUE THREAD

**Issue by xuyangnet** [Nerver4Ever/SevenSha1UIAdvancedHelper#76]
已经降级了   最新版本不知道什么原因都显示转存失败    降级到3.6后  全部成功。

**Comment by Nemong** [comment]
请问3.6可以手动去除分隔符吗？

**Comment by Seaspirit** [comment]
3.6我也用不了。哪里的问题呢

**Comment by xuyangnet** [comment]
> 请问3.6可以手动去除分隔符吗？

好像可以的吧~   再说有自动偏手动干啥

**Comment by xuyangnet** [comment]
> 3.6我也用不了。哪里的问题呢

按说不应该，我是试了好多次，最终换了3.6直接就好使了，根据回馈，大多数都好使，所以还是看看浏览器或者插件是不是有冲突什么的。

**Comment by flylj999** [comment]
哪里有115 秒传链接的 资源啊

**Comment by Nemong** [comment]
感谢回复，我回头再试试
2022年11月19日 +0800 16:57 xuyangnet ***@***.***>，写道：
