### ISSUE TITLE
关于115的拦截

### ISSUE THREAD

**Issue by Seaspirit** [Nerver4Ever/SevenSha1UIAdvancedHelper#8]
不知道对不对，我发现115的拦截是基于文件夹或文件名的。

所以我想，能不能出个插件，实现在BT上传或磁链上传的时候也加入分隔符。
不知道有没有可行性。

**Comment by xueziang** [comment]
没有，bt你改文件名就是新的bt文件了，这样根本没办法下载了，因为找不到对应的源文件了
