### ISSUE TITLE
显示正在操作中的，建议点开设置，把最后一行分隔符方案里的生僻字删掉试试

### ISSUE THREAD

**Issue by 28hao** [Nerver4Ever/SevenSha1UIAdvancedHelper#84]
**描述一下遇到的问题**
在此输入问题

**复现问题**
1. 如有可能，附上sha1或者将所有sha1打包成一个txt，再附上该txt的sha1
2. 附上脚本版本号以及浏览器版本和运行环境。“油猴图标”-》“脚本与环境设置”

**截图**
1.如有可能附上提示出错截图
2. 附上F12，cosnole页面，红色的报错。从一开始就需要截图，不要只截图最后的

**Comment by bigbigking** [comment]
亲测有效   3.5 魔改版   2022年12月15日

**Comment by android0221** [comment]
> 亲测有效 3.5魔改版 2022年12月15日

可以用是可以用，但是点击开始sha1转存后，没有弹窗进度，只能干等，有什么办法吗？
