### ISSUE TITLE
删

### ISSUE THREAD

**Issue by gl1031** [Nerver4Ever/SevenSha1UIAdvancedHelper#85]
删

**Comment by Streamer-stars** [comment]
找了很多脚本都不能用，没想到这个居然可以，大佬厉害
![image](https://user-images.githubusercontent.com/76718993/208723090-14d1b67e-8595-459a-9714-6a12182fcf6e.png)

**Comment by confeather** [comment]
您就是唯一真神啊！其他所有的脚本我试了都不好使，就这个有效

**Comment by zhaifanhua** [comment]
真的可以！

**Comment by qianye599** [comment]
唯一真神

**Comment by 5jwoj** [comment]
实测可用，大佬威5

**Comment by Bob0s** [comment]
大佬威5

**Comment by And-blue** [comment]
大佬666

**Comment by figral** [comment]
登录膜拜

**Comment by jaysong2022** [comment]
感谢大佬，下了无数个都不行，专门注册感谢！

**Comment by Weidows** [comment]
好人一胎生八个!

**Comment by zengruzhen** [comment]
牛牛牛
![image](https://user-images.githubusercontent.com/18514089/210173065-f89d3cf7-6780-4ca1-924b-8654dc366fa0.png)

**Comment by aacy888** [comment]
ed2k链接全部转存失败，115链接成功

**Comment by luyu911** [comment]
非常之好用，唯一有效

**Comment by windflyer** [comment]
非常好用，115 sha 全部成功

**Comment by Seaspirit** [comment]
目前唯一能用，感谢大佬分享。

**Comment by willcool** [comment]
大佬真的牛逼

**Comment by microka** [comment]
感谢大佬！请问大佬【默认保存至当前位置】功能有机会加上吗？

**Comment by i990049** [comment]
楼主会不会修改油猴脚本？
阿里云盘导出115sha1链接助手ui优化版
今天阿里修改视频端口，小白羊、webdav。alist全部作废了

**Comment by KiritoGuugk** [comment]
为什么删了啊
