### ISSUE TITLE
可能参数不正确(?)：request invalid

### ISSUE THREAD

**Issue by abcfy2** [Nerver4Ever/SevenSha1UIAdvancedHelper#9]
**描述一下遇到的问题**
现在是不是又挂了，所有的秒链都会提示`可能参数不正确(?)：request invalid`

**复现问题**
3.5 版本

**截图**
![image](https://user-images.githubusercontent.com/5327677/169826982-636a4a6a-8ce6-4a62-94dd-d74cd6460da3.png)

![image](https://user-images.githubusercontent.com/5327677/169826898-b75880a8-d9b0-43b1-a790-3bc0e1281a99.png)

**Comment by XIJINIAN** [comment]
Chrome 也是这个错误捏

**Comment by v-limc** [comment]
v3.6 依然有这个问题，尝试了Edge、Chrome都是这样
